name: Bump ruby-bacon version

on:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Update package version and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        sed -i -e 's/"1\.0\.1\.[[:alnum:]]*"/"1.0.1.'$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c20)'"/g' ruby-bacon/ruby-bacon.gemspec
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
