name: Bump ruby-bacon version

on:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Update package version and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        sed -i -e 's/"1\.0\.1\.[[:alnum:]]*"/"1.0.1.'$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c20)'"/g' ruby-bacon/ruby-bacon.gemspec
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x
    - name: Add GPR token to template credentials file
      run: sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' ruby-bacon/credentials
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build the gem
      run: gem build ruby-bacon/ruby-bacon.gemspec
    - name: Publish the package
      run: gem push ruby-bacon/*.gem --key github --host https://rubygems.pkg.github.com/bbq-beets --config-file ruby-bacon/credentials
